# Generated by Django 4.2.2 on 2024-04-05 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChessGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('p', 'Pending'), ('a', 'Active'), ('f', 'Finished')], default='m', help_text='Disponibilidad del libro', max_length=1)),
                ('board_state', models.CharField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', help_text='El estado del tablero actualmente', max_length=1000)),
                ('start_time', models.DateField(help_text='La fecha a la que se creo la partida', max_length=11)),
                ('end_time', models.DateField(blank=True, help_text='La fecha a la que se creo la partida', max_length=11, null=True)),
                ('timeControl', models.IntegerField(help_text='The ammount of time that each player have to make a move')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, help_text='The rate of the player')),
                ('name', models.CharField(help_text='The name of the player', max_length=40)),
            ],
            options={
                'ordering': ['rating'],
            },
        ),
        migrations.CreateModel(
            name='ChessMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_from', models.CharField(help_text='The coords from where the figure is moved from', max_length=2)),
                ('move_to', models.CharField(help_text='The coordenates where the figure is moved to', max_length=2)),
                ('promotion', models.CharField(choices=[('q', 'queen'), ('r', 'rook'), ('n', 'knight'), ('b', 'bishop')], help_text='The figure that is promoted to', max_length=8, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='models.chessgame')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='models.player')),
            ],
        ),
        migrations.AddField(
            model_name='chessgame',
            name='blackPlayer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='black_layer', to='models.player'),
        ),
        migrations.AddField(
            model_name='chessgame',
            name='whitePlayer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='white_player', to='models.player'),
        ),
        migrations.AddField(
            model_name='chessgame',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='winner', to='models.player'),
        ),
    ]
