# Generated by Django 4.2.2 on 2024-04-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='password',
            field=models.CharField(default='', help_text='password of the player', max_length=30),
        ),
    ]
