# Generated by Django 4.2.2 on 2024-04-07 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_player_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='password',
        ),
    ]
