# Generated by Django 4.2.2 on 2024-04-09 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_alter_player_managers_remove_player_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessgame',
            name='whitePlayer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='white_player', to=settings.AUTH_USER_MODEL),
        ),
    ]
