# Generated by Django 4.2.2 on 2024-04-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_alter_chessgame_status_alter_player_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rating',
            field=models.IntegerField(default=-1, help_text='The rate of the player'),
        ),
    ]
