# Generated by Django 4.2.2 on 2024-04-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_alter_player_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessgame',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('ACTIVE', 'active'), ('FINISHED', 'finished')], default='pending', help_text='Estado de la partida', max_length=20),
        ),
    ]
