# Generated by Django 4.2.2 on 2024-04-09 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_alter_chessgame_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessgame',
            name='blackPlayer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blackPlayer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='board_state',
            field=models.TextField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', help_text='Almacena la posición de las piezas en formato FEN'),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Game ending time', null=True, verbose_name='Ending'),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='start_time',
            field=models.DateTimeField(auto_now=True, help_text='Game starting time', null=True, verbose_name='Start'),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('ACTIVE', 'active'), ('FINISHED', 'finished')], default='pending', max_length=64),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='timeControl',
            field=models.CharField(help_text='Control de tiempo para cada jugador', max_length=50, verbose_name='Time Control'),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='whitePlayer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whitePlayer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='winner',
            field=models.ForeignKey(blank=True, help_text='El ganador de la partida. Puede ser nulo si el juego está pendiente o ha terminado en empate.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_won', to=settings.AUTH_USER_MODEL),
        ),
    ]
