# Generated by Django 4.2.2 on 2024-06-10 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_alter_chessgame_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='models.chessgame')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
